### ISSUE TITLE
Can't load the profile

### ISSUE THREAD

**Issue by sinoux** [hacktoolspack/hack-tools#22]
I installed selenium
but in instagram cracking give me this fucking shit

Traceback (most recent call last):
  File "/usr/local/bin/brut3k1t", line 11, in <module>
    load_entry_point('brut3k1t==3.0.1', 'console_scripts', 'brut3k1t')()
  File "build/bdist.linux-x86_64/egg/brut3k1t/__main__.py", line 89, in main
  File "build/bdist.linux-x86_64/egg/brut3k1t/web.py", line 47, in execute
  File "build/bdist.linux-x86_64/egg/brut3k1t/web.py", line 56, in usercheck
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 80, in __init__
    self.binary, timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/extension_connection.py", line 52, in __init__
    self.binary.launch_browser(self.profile, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 68, in launch_browser
    self._wait_until_connectable(timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 108, in _wait_until_connectable
    % (self.profile.path))
selenium.common.exceptions.WebDriverException: Message: Can't load the profile. Profile Dir: /tmp/tmpXwEyU3 If you specified a log_file in the FirefoxBinary constructor, check it for details.

please help me!!!!!

**Comment by sinoux** [comment]
#Can't load the profile

**Comment by hacktoolspack** [comment]
I will try to remedy this problem as soon as possible.

**Comment by hacktoolspack** [comment]
i have updated the requirements off brut3k1t please retry and let me know if it works.
